.mode csv

.import /home/yunyi/Documents/smart_contracts/temp/chunk_0.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_1.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_2.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_3.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_4.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_5.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_6.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_7.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_8.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_9.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_10.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_11.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_12.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_13.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_14.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_15.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_16.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_17.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_18.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_19.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_20.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_21.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_22.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_23.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_24.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_25.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_26.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_27.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_28.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_29.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_30.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_31.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_32.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_33.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_34.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_35.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_36.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_37.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_38.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_39.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_40.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_41.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_42.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_43.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_44.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_45.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_46.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_47.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_48.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_49.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_50.csv transactions
.import /home/yunyi/Documents/smart_contracts/temp/chunk_51.csv transactions
